apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: vertxgtw
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: vertxgtw
  spec:
   output:
     to:
       kind: ImageStreamTag
       name: vertxgtw:latest
   postCommit: {}
   resources: {}
   runPolicy: Serial
   source:    
     git:       
       ref: master
       uri: https://github.com/jarielpa/vertxgtw-ose.git
     type: Git
   strategy:
     dockerStrategy:
       dockerfilePath: Dockerfile     
       from:
         kind: DockerImage
         name: jboss/base-jdk:8
     type: Docker
