apiVersion: v1
kind: Template
metadata:
  name: vertxgtw
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: vertxgtw
    name: vertxgtw
  spec:
    ports:
    - name: 8081-tcp
      port: 8081
      protocol: TCP
      targetPort: 8081
    - name: 8082-tcp
      port: 8082
      protocol: TCP
      targetPort: 8082
    selector:
      app: vertxgtw
      deploymentconfig: vertxgtw
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:    
    labels:
      app: vertxgtw
    name: vertxgtw
  spec:
    replicas: 1
    selector:
      app: vertxgtw
      deploymentconfig: vertxgtw
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
        labels:
          app: vertxgtw
          deploymentconfig: vertxgtw
      spec:
        containers:
        - image: vertxgtw
          imagePullPolicy: Always
          name: vertxgtw
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - vertxgtw
        from:
          kind: ImageStreamTag
          name: vertxgtw:latest        
      type: ImageChange
  status: {}
